spring:
  datasource:
    #如果存在多个数据源，监控的时候可以通过名字来区分开来
    # name: mysql
    #连接数据库的url
    url: jdbc:mysql://localhost:3306/springboot?characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    #连接数据库的账号
    username: root
    #连接数据库的密码
    password: system
    #使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    #扩展插件
    #监控统计用的filter:stat 日志用的filter:log4j 防御sql注入的filter:wall
    filters: stat
    #最大连接池数量
    maxActive: 20
    #初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
    initialSize: 1
    #获取连接时最大等待时间，单位毫秒
    maxWait: 60000
    #最小连接池数量
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    #连接保持空闲而不被驱逐的最长时间
    minEvictableIdleTimeMillis: 300000
    #用来检测连接是否有效的sql，要求是一个查询语句
    validationQuery: SELECT 1 FROM DUAL
    #申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
    testWhileIdle: true
    #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    testOnBorrow: false
    #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    testOnReturn: false
    #是否缓存preparedStatement，即PSCache
    poolPreparedStatements: false
    #要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true
    maxOpenPreparedStatements: -1
  jackson:
    time-zone: GMT+8

#redis配置对应RedisProperties类
  redis:
    host: 127.0.0.1
    post: 6379
    #Redis服务器密码，默认为空，生产中，一定要设置Redis密码
    password:
    #Redis数据库版本号，默认为0
    database: 0
    #Redis连接超时时间，单位：毫秒
    timeout: 0
    #对应RedisProperties.Jedis内部类
    jedis:
      pool:
        #连接池最大连接数，默认为8，使用负数表示没有限制
        max-active: 8
        #默认连接数最小空闲的连接数，默认为8，使用负数表示没有限制
        max-idle: 8
        #默认连接池最小空闲的连接数，默认为0，允许设置0和正数
        min-idle: 0
        #连接池最大阻塞等待时间，单位毫秒，默认为-1，表示不限制
        max-wait: -1
