#redis配置对应RedisProperties类
spring:
  redis:
    host: 127.0.0.1
    post: 6379
    #Redis服务器密码，默认为空，生产中，一定要设置Redis密码
    password:
    #Redis数据库版本号，默认为0
    database: 0
    #Redis连接超时时间，单位：毫秒
    timeout: 0
    #对应RedisProperties.Jedis内部类
    jedis:
      pool:
        #连接池最大连接数，默认为8，使用负数表示没有限制
        max-active: 8
        #默认连接数最小空闲的连接数，默认为8，使用负数表示没有限制
        max-idle: 8
        #默认连接池最小空闲的连接数，默认为0，允许设置0和正数
        min-idle: 0
        #连接池最大阻塞等待时间，单位毫秒，默认为-1，表示不限制
        max-wait: -1