server:
  port: 8081
  servlet:
    context-path: /user-api
spring:
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
#pagehelper分页插件
pagehelper:
  #数据库的方言
  helperDialect: mysql
  #启用合理化，如果pageNum < 1会查询第一页，如果pageNum > pages会查询最后一页
  reasonable: true
mybatis:
  #mapper.xml包地址
  mapper-locations: classpath:mapper/*.xml
  #pojo生成包地址
  type-aliases-package: com.zhoudy.springboot.usermanage.entity.po
