# Spring Task 调度任务的配置，对应 TaskSchedulingProperties 配置类
spring:
  task:
    scheduling:
      thread-name-prefix: zhoudy-demo- # 线程池的线程名的前缀。默认为 scheduling- ，建议根据自己应用来设置
      pool:
        size: 10 # 线程池大小。默认为 1 ，根据自己应用来设置
